In [2]:
import os
import numpy as np
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt
from xgboost import plot_importance, plot_tree
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV

In [39]:
df = pd.read_csv("../data/processed/processed_data.csv")
df.drop(index=[0,1], inplace=True)
df.reset_index(drop=True, inplace=True)

In [40]:
df.head()

,Date,Close,High,Low,Open,Volume,EMA_9,SMA_5,SMA_10,SMA_15,SMA_30,RSI,MACD,MACD_signal,target
0,2020-02-20,5461.500000,5544.312737,5436.656179,5540.172100,136724500,5565.579552,5561.703711,5585.305029,5544.864714,5593.862402,58.273480,-14.356222,-6.040940,1
1,2020-02-21,5478.062012,5515.327740,5461.499466,5465.640102,98261000,5544.763641,5529.406641,5573.297168,5536.859473,5589.859782,62.963041,-19.161183,-8.664988,0
2,2020-02-24,5403.530762,5465.640311,5391.108852,5436.655855,84910000,5531.423316,5518.640625,5561.289307,5544.312630,5586.823275,43.801683,-28.652904,-12.662572,1
3,2020-02-25,5407.671387,5432.515206,5391.108840,5424.233933,86446500,5505.844805,5486.343555,5539.758008,5549.005371,5580.750342,29.166303,-35.432603,-17.216578,0
4,2020-02-26,5316.577637,5411.812283,5316.577637,5382.827825,92824500,5486.210121,5459.015332,5519.054834,5545.140820,5571.364893,22.413523,-47.607281,-23.294719,0

In [41]:
print(df.dtypes)

Date            object
Close          float64
High           float64
Low            float64
Open           float64
Volume           int64
EMA_9          float64
SMA_5          float64
SMA_10         float64
SMA_15         float64
SMA_30         float64
RSI            float64
MACD           float64
MACD_signal    float64
target           int64
dtype: object

Price,Close,High,Low,Open,Volume,target
Ticker,BBCA.JK,BBCA.JK,BBCA.JK,BBCA.JK,BBCA.JK,
Date,,,,,,
2020-01-02,5540.172363,5614.703830,5531.891089,5544.313000,49445000,1
2020-01-03,5631.265625,5631.265625,5569.156078,5589.859260,47755500,0
2020-01-06,5577.437988,5589.859899,5540.172256,5565.016077,27300000,1
2020-01-07,5581.578613,5606.422435,5573.297339,5577.437976,45022500,0
2020-01-08,5531.892090,5585.720381,5523.610814,5523.610814,53692500,1